### ISSUE TITLE
g r e t w u r k

### ISSUE THREAD

**Issue by stevenchung** [andreisk/drinks-list#1]
Ａｎｄｒｅｉ， ｙｏｕ ｇｏｔｔａ ｓｔｏｐ．  Ｙｏｕ＇ｖｅ ｍａｄｅ ａ ｄｕｎｋ ａｌｍｏｓｔ ｅｖｅｒｙ ｈｏｕｒ ｆｏｒ ｔｈｅ ｐａｓｔ ｄｅｃａｄｅ．  Ｉ ｋｎｏｗ ｉｔ＇ｓ ｈａｒｄ ｔｏ ｂｅ ｎｏｒｍａｌ， ｂｕｔ ｔｈｉｓ ｓｔｕｎｔｉｎｇ ａｄｄｉｃｔｉｏｎ ｉｓ ｇｏｉｎｇ ｔｏ ｄｅｓｔｒｏｙ ｙｏｕ．  Ｐｌｅａｓｅ， Ａｎｄｒｅｉ．  Ｉｔ＇ｓ ｆｏｒ ｙｏｕｒ ｏｗｎ ｇｏｏｄ．

**Comment by andreisk** [comment]
...
